service: aws-node-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:us-west-2:162918828586:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertitem.handler
    events:
      - httpApi:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchitems.js
    events:
      - httpApi:
          path: /item
          method: get
  fetchItem:
    handler: src/fetchitem.js
    events:
      - httpApi:
          path: /item/{id}
          method: get
  updateItem:
    handler: src/updateitem.js
    events:
      - httpApi:
          path: /item/{id}
          method: put

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH